<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cube</string>
	</array>
	<key>name</key>
	<string>cubeLUT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.cube</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.cube</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*((TITLE).*$\n?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cube</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.cube</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*((LUT_1D_SIZE|LUT_3D_SIZE).*$\n?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cube</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.cube.cube</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*((DOMAIN_MIN|DOMAIN_MAX|LUT_1D_INPUT_RANGE|LUT_3D_INPUT_RANGE).*$\n?)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>regular expression for floating point numbers..</string>
			<key>match</key>
			<string>([-+]?[0-9]*\.[0-9]*)</string>
			<key>name</key>
			<string>constant.numeric.float.cube</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>regular expression for integer numbers..</string>
			<key>match</key>
			<string>\b[-+]?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.cube</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cube</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>string match..</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cube</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cube</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.hashtag.cube</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cube</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>line comment match..</string>
			<key>match</key>
			<string>\s*((#).*$\n?)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cube</string>
	<key>uuid</key>
	<string>3260e1c6-0548-4245-8c8c-06c278014d33</string>
</dict>
</plist>
